package io.github.joke.percolate.processor.internal.stages.expand;

import io.github.joke.percolate.processor.internal.graph.AccessPath;
import io.github.joke.percolate.processor.internal.graph.Location;
import io.github.joke.percolate.processor.internal.graph.MethodScope;
import io.github.joke.percolate.processor.internal.graph.PortBinding;
import io.github.joke.percolate.processor.internal.graph.Scope;
import io.github.joke.percolate.processor.internal.graph.SourceLocation;
import io.github.joke.percolate.spi.OperationSpec;
import io.github.joke.percolate.spi.ResolveCtx;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.IntStream;
import javax.lang.model.element.ExecutableElement;
import javax.lang.model.element.Modifier;
import lombok.RequiredArgsConstructor;

/**
 * Bind-time self-call guard for the expansion driver: a method may not be landed calling another method's whole
 * <b>whole parameter</b> ({@code this.m(param)}) when that call target shares its own (parameter types, return type)
 * <b>shape</b> and is itself {@code abstract} (i.e. also generated by this same run) — a degenerate recursion the
 * cost model cannot see. This covers two cases: (1) the true self-call, where the call target <em>is</em> the
 * enclosing method, and (2) a mutual 2-cycle between two <em>different</em> same-shaped abstract methods (e.g. two
 * mapper methods both {@code Optional<String> -> String}, differing only in a {@code @Nullable} on the return —
 * invisible to {@link ResolveCtx#isSameType}, the same annotation-blind identity {@code MethodCallBridge}'s candidate
 * match already uses, which is exactly why the two methods are interchangeable candidates for each other in the
 * first place) — each would otherwise offer the other as its cheapest, non-partial producer, since the driver never
 * models a call target's own body: a call binds to the enclosing scope's own in-scope value, never to the callee's
 * cost, so over-emit + cost-prune cannot reject either case — the recursion only exists across the two methods'
 * independently-computed plans, never as a cost dependency the fold can see.
 *
 * <p>A self-call on a <b>sub-part</b> of the parameter (an {@code ACCESS} source such as {@code src.getNext()}) or a
 * container element (a child scope) is <b>not</b> refused; delegation to a call target of a <em>different</em> shape
 * is <b>not</b> refused (the everyday "conversion method" case, e.g. {@code toView(Address)} reused by
 * {@code map(Customer)}); and delegation to a same-shaped call target that is a {@code default} method (a fixed,
 * developer-written body, never itself re-entrant into this run) is <b>not</b> refused either. The guard is
 * per-binding: it compares the spec's neutral {@link OperationSpec#getCallTarget() call target} to the enclosing
 * {@link MethodScope}'s method by shape (parameter types + return type, ignoring name, via the {@link ResolveCtx}
 * type-query seam so annotations never leak in through {@code TypeMirror#toString}) and checks whether a bound port
 * is that method's own parameter-root {@code LEAF} {@link SourceLocation}. It never inspects the label. A cohesive
 * collaborator the driver delegates to (mirroring {@link SourceCandidates}), so the driver stays the work-list
 * dispatch + landing site.
 */
@RequiredArgsConstructor
final class SelfCallGuard {

    private final ResolveCtx ctx;

    /** Whether landing {@code spec} bound by {@code ports} in {@code scope} would be a whole-parameter self-call. */
    boolean refuses(final Scope scope, final OperationSpec spec, final List<PortBinding> ports) {
        if (!isSameShapedAbstractSelfCallTarget(scope, spec)) {
            return false;
        }
        final var parameterRoots = parameterRootLocations(((MethodScope) scope).getMethod());
        return ports.stream()
                .anyMatch(binding -> parameterRoots.contains(binding.getSource().getLocation()));
    }

    boolean isSameShapedAbstractSelfCallTarget(final Scope scope, final OperationSpec spec) {
        if (!(scope instanceof MethodScope) || spec.getCallTarget().isEmpty()) {
            return false;
        }
        final var callTarget = spec.getCallTarget().get();
        final var method = ((MethodScope) scope).getMethod();
        return callTarget.getModifiers().contains(Modifier.ABSTRACT) && sameShape(callTarget, method);
    }

    /** The whole-parameter source locations of {@code method}: a {@code LEAF} {@link SourceLocation} per parameter. */
    static Set<Location> parameterRootLocations(final ExecutableElement method) {
        return method.getParameters().stream()
                .map(parameter -> (Location) new SourceLocation(
                        AccessPath.of(parameter.getSimpleName().toString())))
                .collect(Collectors.toUnmodifiableSet());
    }

    /**
     * Whether {@code a} and {@code b} declare the same parameter types and return type, ignoring method name — via
     * {@link ResolveCtx#isSameType}, not {@code TypeMirror#toString}, so a {@code @Nullable} type-use annotation
     * (rendered into {@code toString()} but not part of type identity) can never make two otherwise-identical
     * shapes look different.
     */
    boolean sameShape(final ExecutableElement a, final ExecutableElement b) {
        final var paramsA = a.getParameters();
        final var paramsB = b.getParameters();
        return paramsA.size() == paramsB.size()
                && ctx.isSameType(a.getReturnType(), b.getReturnType())
                && IntStream.range(0, paramsA.size())
                        .allMatch(i -> ctx.isSameType(
                                paramsA.get(i).asType(), paramsB.get(i).asType()));
    }
}
