package io.github.joke.percolate.processor.internal.stages.expand;

import io.github.joke.percolate.processor.internal.graph.AccessPath;
import io.github.joke.percolate.processor.internal.graph.AddValue;
import io.github.joke.percolate.processor.internal.graph.Location;
import io.github.joke.percolate.processor.internal.graph.MethodScope;
import io.github.joke.percolate.processor.internal.graph.Scope;
import io.github.joke.percolate.processor.internal.graph.SourceLocation;
import io.github.joke.percolate.spi.BoundPort;
import io.github.joke.percolate.spi.Constraint;
import io.github.joke.percolate.spi.Offer;
import io.github.joke.percolate.spi.OperationSpec;
import io.github.joke.percolate.spi.ResolveCtx;
import io.github.joke.percolate.spi.Subjects;
import java.util.List;
import java.util.Optional;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.IntStream;
import javax.lang.model.element.ExecutableElement;
import javax.lang.model.element.Modifier;

// The engine's own built-in landing constraint (design D8 of change decouple-engine-from-strategy-semantics,
// replacing the bespoke SelfCallGuard): a method may not land calling another method's whole whole parameter
// (this.m(param)) when that call target shares its own (parameter types, return type) shape and is itself
// abstract (i.e. also generated by this same run) — a degenerate recursion the cost model cannot see. This
// covers two cases: (1) the true self-call, where the call target is the enclosing method, and (2) a mutual
// 2-cycle between two different same-shaped abstract methods — each would otherwise offer the other as its
// cheapest, non-partial producer, since a call binds to the enclosing scope's own in-scope value, never to the
// callee's cost, so over-emit + cost-prune cannot reject either case.
//
// A self-call on a sub-part of the parameter (an ACCESS source) or a container element is not refused;
// delegation to a call target of a different shape is not refused; and delegation to a same-shaped call target
// that is a default method is not refused either. Applied by the driver through the same admissibility
// mechanism as any reader-contributed Constraint — there is exactly one admissibility mechanism in the engine,
// so this is not a second, bespoke landing filter.
final class SelfCallConstraint implements Constraint {

    private final ResolveCtx ctx;
    private final Scope scope;

    SelfCallConstraint(final ResolveCtx ctx, final Scope scope) {
        this.ctx = ctx;
        this.scope = scope;
    }

    @Override
    public Optional<Offer.Refusal> check(final OperationSpec candidate, final List<BoundPort> boundPorts) {
        if (!isSameShapedAbstractSelfCallTarget(candidate)) {
            return Optional.empty();
        }
        final var parameterRoots = parameterRootLocations(((MethodScope) scope).getMethod());
        final var refuses = boundPorts.stream()
                .anyMatch(bound -> parameterRoots.contains(((AddValue) bound.getValueIdentity()).getLocation()));
        if (!refuses) {
            return Optional.empty();
        }
        return Optional.of(new Offer.Refusal(
                Subjects.none(),
                "landing '" + candidate.getLabel()
                        + "' here would call the method being generated on its own whole parameter — a degenerate"
                        + " self-call"));
    }

    boolean isSameShapedAbstractSelfCallTarget(final OperationSpec spec) {
        if (!(scope instanceof MethodScope) || spec.getCallTarget().isEmpty()) {
            return false;
        }
        final var callTarget = spec.getCallTarget().get();
        final var method = ((MethodScope) scope).getMethod();
        return callTarget.getModifiers().contains(Modifier.ABSTRACT) && sameShape(callTarget, method);
    }

    // The whole-parameter source locations of method: a LEAF SourceLocation per parameter.
    Set<Location> parameterRootLocations(final ExecutableElement method) {
        return method.getParameters().stream()
                .map(parameter -> (Location) new SourceLocation(
                        AccessPath.of(parameter.getSimpleName().toString())))
                .collect(Collectors.toUnmodifiableSet());
    }

    // Whether a and b declare the same parameter types and return type, ignoring method name.
    boolean sameShape(final ExecutableElement a, final ExecutableElement b) {
        final var paramsA = a.getParameters();
        final var paramsB = b.getParameters();
        return paramsA.size() == paramsB.size()
                && ctx.isSameType(a.getReturnType(), b.getReturnType())
                && IntStream.range(0, paramsA.size())
                        .allMatch(i -> ctx.isSameType(
                                paramsA.get(i).asType(), paramsB.get(i).asType()));
    }
}
