plugins {
    id 'java'
    id 'groovy'
    id 'percolate.conventions'
}

dependencies {
    annotationProcessor platform(project(':dependencies'))
    annotationProcessor project(':percolate')
    annotationProcessor 'io.github.joke.jspecify:processor'

    testAnnotationProcessor platform(project(':dependencies'))
    testAnnotationProcessor 'io.github.joke.jspecify:processor'

    compileOnly platform(project(':dependencies'))
    compileOnly project(':annotations')
    compileOnly 'org.jspecify:jspecify'

    testImplementation platform(project(':dependencies'))
    testImplementation 'org.spockframework:spock-core'
    testImplementation 'org.apache.groovy:groovy'

    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testRuntimeOnly 'org.slf4j:slf4j-simple'
}
