plugins {
    id 'java'
    id 'percolate.conventions'
}

dependencies {
    annotationProcessor project(':percolate')

    compileOnly platform(project(':dependencies'))
    compileOnly project(':annotations')
    compileOnly 'org.jspecify:jspecify'
}

tasks.register('smokeRun', JavaExec) {
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'com.example.smoke.SmokeMain'
}

tasks.named('check') {
    dependsOn 'smokeRun'
}
