package io.github.joke.percolate.spi.builtins.deferral;

import io.github.joke.percolate.lib.javapoet.ClassName;
import io.github.joke.percolate.lib.javapoet.CodeBlock;
import io.github.joke.percolate.spi.ExpansionStrategy;
import io.github.joke.percolate.spi.Nullability;
import io.github.joke.percolate.spi.OperationCodegen;
import io.github.joke.percolate.spi.OperationSpec;
import io.github.joke.percolate.spi.Port;
import io.github.joke.percolate.spi.ProduceDemand;
import io.github.joke.percolate.spi.ResolveCtx;
import io.github.joke.percolate.spi.Weights;
import java.util.List;
import java.util.stream.Stream;

/**
 * Test-only fixture, registered via {@code META-INF/services} for the {@code strategies-builtin} test classpath
 * only: proves the round-based deferral silence proven by {@code decouple-engine-from-strategy-semantics}'s design
 * D14 ("a mapper deferred with a transient diagnostic realises silently on the co-processor's round"). It produces
 * {@code examples.deferral.Widget} only once that class is resolvable — genuinely absent in the compilation's first
 * round and generated by a co-processor ({@code WidgetGeneratingProcessor}) partway through, exactly the shape of a
 * Lombok-generated member appearing on a later round. Inert for every other test on the same classpath: it applies
 * only to the fixture type unique to this one test.
 */
public final class DeferredWidgetFixtureStrategy implements ExpansionStrategy {

    private static final String WIDGET = "examples.deferral.Widget";
    private static final String STRING = "java.lang.String";
    private static final ClassName WIDGET_TYPE = ClassName.get("examples.deferral", "Widget");

    @Override
    public Stream<OperationSpec> expand(final ProduceDemand demand, final ResolveCtx ctx) {
        if (!ctx.isType(demand.targetType(), WIDGET)) {
            return Stream.empty();
        }
        if (ctx.typeElementNamed(WIDGET) == null) {
            // Not generated yet this round — the same "no producer this round" a Lombok-pending member causes.
            return Stream.empty();
        }
        final var stringElement = ctx.typeElementNamed(STRING);
        if (stringElement == null) {
            return Stream.empty();
        }
        final var port = new Port("value", stringElement.asType(), Nullability.NON_NULL);
        final OperationCodegen codegen = inputs -> CodeBlock.of("new $T()", WIDGET_TYPE);
        return Stream.of(OperationSpec.of(
                "new Widget()", codegen, Weights.STEP, List.of(port), demand.targetType(), Nullability.NON_NULL));
    }
}
