plugins {
    id 'java-library'
    id 'groovy'
    id 'maven-publish'
    id 'percolate.conventions'
}

dependencies {
    annotationProcessor platform(project(':dependencies'))
    annotationProcessor 'io.github.joke.jspecify:processor'

    compileOnly platform(project(':dependencies'))
    compileOnly 'org.jspecify:jspecify'

    testAnnotationProcessor platform(project(':dependencies'))
    testAnnotationProcessor 'io.github.joke.jspecify:processor'

    testImplementation platform(project(':dependencies'))
    testImplementation 'org.spockframework:spock-core'
    testImplementation 'org.apache.groovy:groovy'
    testImplementation 'com.google.testing.compile:compile-testing'
    testImplementation 'org.jspecify:jspecify'

    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testRuntimeOnly 'org.mockito:mockito-junit-jupiter'
    testRuntimeOnly 'org.slf4j:slf4j-simple'
}
